apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
  labels:
    app: libretranslate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      labels:
        app: libretranslate
    spec:
      containers:
      - name: libretranslate
        image: libretranslate/libretranslate:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: LT_LOAD_ONLY
          value: "en,fr,it"
---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate-service
spec:
  selector:
    app: libretranslate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP